"""BigQuery writer: staging loads + MERGE upserts, child-row replacement."""

import logging
import os
import random
import time
import uuid
from typing import Any

from google.api_core.exceptions import BadRequest, Conflict
from google.cloud import bigquery

from .schema import TABLES
from .state import SyncStateStore

logger = logging.getLogger(__name__)

# Attempts for DML that can collide with a concurrent mutation of the same
# table (parallel webhook tasks, scheduled ticks)
_CONCURRENT_ATTEMPTS = 5

# Max distinct keys inlined into a literal DELETE+INSERT upsert. Above this we
# fall back to MERGE: the id list would bloat the SQL, and a batch that large
# is a backfill/dump chunk whose full-scan MERGE cost amortizes over many rows.
# Webhook batches and incremental sweeps sit far below this.
_LITERAL_KEY_MAX = 2000


class BigQueryWriter:
    def __init__(self, project: str | None = None, dataset: str | None = None):
        self.project = project or os.environ["GCP_PROJECT_ID"]
        self.dataset = dataset or os.environ.get("BQ_DATASET", "brightpearl")
        self.client = bigquery.Client(project=self.project)
        # Cached, batch-flushed sync_state (see sync/state.py). Callers read
        # watermarks with bq.state.get() and record runs with bq.state.record();
        # tick()/CLI flush once per pass instead of one MERGE per resource.
        self.state = SyncStateStore(self)

    def _load_json(self, rows: list[dict[str, Any]], target: str, job_config) -> None:
        """load_table_from_json with a fresh job id on 409 Conflict.

        A client-side timeout can re-submit a load with the same autogenerated
        job id; BigQuery rejects the duplicate even though the first attempt
        may have succeeded. Retrying with an explicit new id is always safe
        here because staging loads and truncate loads are WRITE_TRUNCATE.
        """
        try:
            self.client.load_table_from_json(rows, target, job_config=job_config).result()
        except Conflict:
            logger.warning("load job conflict on %s; retrying with fresh job id", target)
            self.client.load_table_from_json(
                rows, target, job_config=job_config, job_id=f"retry_{uuid.uuid4().hex}"
            ).result()

    def _table_ref(self, name: str) -> str:
        return f"{self.project}.{self.dataset}.{name}"

    def _dml(self, sql: str):
        """query_and_wait with backoff on concurrent-update aborts.

        BigQuery allows one mutating statement per table at a time; when two
        collide it aborts one with a 400 mentioning "concurrent update".
        Retrying is safe here: every mutation in this module is idempotent
        (keyed MERGEs, DELETE+INSERT transactions, soft-delete UPDATEs).
        """
        for attempt in range(_CONCURRENT_ATTEMPTS):
            try:
                return self.client.query_and_wait(sql)
            except BadRequest as e:
                if "concurrent update" not in str(e) or attempt == _CONCURRENT_ATTEMPTS - 1:
                    raise
                delay = 2**attempt + random.random()
                logger.warning(
                    "concurrent update abort (attempt %d/%d); retrying in %.1fs",
                    attempt + 1, _CONCURRENT_ATTEMPTS, delay,
                )
                time.sleep(delay)

    def ensure_tables(self) -> None:
        for name, spec in TABLES.items():
            # Cluster on whatever column MERGE/DELETE actually filters by —
            # the parent key for child-of tables (order_rows' DELETE filters
            # on order_id, not its own order_row_id), else the MERGE key.
            # Without this every upsert/delete full-scans the target table
            # (BigQuery on-demand pricing bills by bytes scanned, not rows
            # touched) — see the 2026-07 billing investigation.
            cluster_field = spec["child_of"][1] if "child_of" in spec else spec["key_field"]
            table = bigquery.Table(self._table_ref(name), schema=spec["schema"])
            table.clustering_fields = [cluster_field]
            self.client.create_table(table, exists_ok=True)
        # Additive migrations for pre-existing tables
        self.client.query_and_wait(
            f"ALTER TABLE `{self._table_ref('sync_state')}` "
            "ADD COLUMN IF NOT EXISTS watermark_id INT64"
        )
        for table in ("orders", "products", "contacts"):
            self.client.query_and_wait(
                f"ALTER TABLE `{self._table_ref(table)}` "
                "ADD COLUMN IF NOT EXISTS is_deleted BOOL, "
                "ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP"
            )

    def mark_deleted(self, table: str, key_field: str, ids: list[int]) -> int:
        """Soft-delete records (destroyed webhooks / reconciliation sweeps).

        ids are interpolated into the SQL, so they MUST be ints — coerced here
        rather than trusting callers, since a future caller passing raw strings
        would otherwise open a DML-injection path.
        """
        if not ids:
            return 0
        id_list = ", ".join(str(int(i)) for i in ids)
        self._dml(
            f"UPDATE `{self._table_ref(table)}` "
            f"SET is_deleted = TRUE, deleted_at = CURRENT_TIMESTAMP() "
            f"WHERE {key_field} IN ({id_list}) AND NOT IFNULL(is_deleted, FALSE)"
        )
        return len(ids)

    def ensure_table(
        self,
        name: str,
        schema: list[bigquery.SchemaField],
        cluster_fields: list[str] | None = None,
    ) -> None:
        table = bigquery.Table(self._table_ref(name), schema=schema)
        if cluster_fields:
            table.clustering_fields = cluster_fields
        self.client.create_table(table, exists_ok=True)

    def _load_staging(
        self,
        name: str,
        rows: list[dict[str, Any]],
        schema: list[bigquery.SchemaField] | None = None,
    ) -> str:
        # Unique per operation: a webhook flush and a scheduled tick can hit
        # the same table concurrently and must not clobber each other's
        # staging. Callers drop the table in a finally block.
        staging = self._table_ref(f"_stg_{name}_{uuid.uuid4().hex[:8]}")
        self._load_json(
            rows,
            staging,
            bigquery.LoadJobConfig(
                schema=schema or TABLES[name]["schema"],
                write_disposition="WRITE_TRUNCATE",
            ),
        )
        return staging

    def _drop(self, table_ref: str) -> None:
        self.client.delete_table(table_ref, not_found_ok=True)

    def truncate_load(
        self,
        name: str,
        rows: list[dict[str, Any]],
        schema: list[bigquery.SchemaField],
        cluster_fields: list[str] | None = None,
    ) -> int:
        """Replace the whole table (small reference/mutable resources)."""
        self.ensure_table(name, schema, cluster_fields)
        self._load_json(
            rows,
            self._table_ref(name),
            bigquery.LoadJobConfig(schema=schema, write_disposition="WRITE_TRUNCATE"),
        )
        return len(rows)

    def upsert(
        self,
        name: str,
        rows: list[dict[str, Any]],
        schema: list[bigquery.SchemaField] | None = None,
        key: str | None = None,
    ) -> int:
        """Upsert rows into the target table keyed on the table's key field.

        Staging is deduped on the key (keeping the freshest when_upserted) so
        overlapping pages or duplicate webhook deliveries stay idempotent.
        Schema/key come from TABLES unless supplied (dynamic search dumps).

        Small integer-keyed batches take a literal-keyed DELETE + INSERT path;
        everything else falls back to a staging-join MERGE. Both reach the same
        end state (one freshest row per key), but only the literal `key IN (…)`
        predicate lets BigQuery prune the clustered target — a MERGE whose match
        keys come from the staging subquery full-scans the target every call
        (orders: whole table vs a few blocks). See the 2026-07-13 billing
        investigation. Large batches (backfills, 25k-row dump chunks) exceed the
        inline-id cap and use MERGE, whose full scan amortizes over many rows.
        """
        if not rows:
            return 0
        if schema is None:
            spec = TABLES[name]
            schema, key = spec["schema"], spec["key_field"]
        staging = self._load_staging(name, rows, schema)
        target = self._table_ref(name)
        cols = [f.name for f in schema]
        insert_cols = ", ".join(cols)
        order_col = "last_run_at" if name == "sync_state" else "when_upserted"
        deduped = (
            f"SELECT * EXCEPT(_rn) FROM ("
            f"SELECT *, ROW_NUMBER() OVER "
            f"(PARTITION BY {key} ORDER BY {order_col} DESC) AS _rn "
            f"FROM `{staging}`) WHERE _rn = 1"
        )
        ids = list(dict.fromkeys(r.get(key) for r in rows))
        use_literal = 0 < len(ids) <= _LITERAL_KEY_MAX and all(
            isinstance(v, int) and not isinstance(v, bool) for v in ids
        )
        try:
            if use_literal:
                # Idempotent on retry: DELETE+INSERT for these exact keys inside
                # one transaction leaves one row per key regardless of prior state.
                id_list = ", ".join(str(v) for v in ids)
                self._dml(
                    "BEGIN TRANSACTION;\n"
                    f"DELETE FROM `{target}` WHERE {key} IN ({id_list});\n"
                    f"INSERT INTO `{target}` ({insert_cols})\n"
                    f"SELECT {insert_cols} FROM ({deduped});\n"
                    "COMMIT TRANSACTION;"
                )
            else:
                updates = ", ".join(f"T.{c} = S.{c}" for c in cols if c != key)
                insert_vals = ", ".join(f"S.{c}" for c in cols)
                self._dml(
                    f"MERGE `{target}` T USING ({deduped}) S "
                    f"ON T.{key} = S.{key} "
                    f"WHEN MATCHED THEN UPDATE SET {updates} "
                    f"WHEN NOT MATCHED THEN INSERT ({insert_cols}) VALUES ({insert_vals})"
                )
        finally:
            self._drop(staging)
        return len(rows)

    def replace_children(
        self,
        name: str,
        parent_field: str,
        parent_ids: list[int],
        rows: list[dict[str, Any]],
        schema: list[bigquery.SchemaField] | None = None,
    ) -> int:
        """Replace all child rows for the given parents (handles deleted lines).

        Delete + insert run in one BigQuery transaction so a crash between
        them can't leave parents without their rows.
        """
        if not parent_ids:
            return 0
        target = self._table_ref(name)
        cols = ", ".join(f.name for f in (schema or TABLES[name]["schema"]))
        # Coerce to int — parent_ids are interpolated into the DELETE below.
        ids = ", ".join(str(int(i)) for i in parent_ids)
        delete_sql = f"DELETE FROM `{target}` WHERE {parent_field} IN ({ids});"
        if not rows:
            self._dml(delete_sql)
            return 0
        staging = self._load_staging(name, rows, schema)
        try:
            self._dml(
                "BEGIN TRANSACTION;\n"
                + delete_sql
                + f"\nINSERT INTO `{target}` ({cols}) SELECT {cols} FROM `{staging}`;\n"
                + "COMMIT TRANSACTION;"
            )
        finally:
            self._drop(staging)
        return len(rows)

    def query(self, sql: str) -> list[dict[str, Any]]:
        return [dict(r) for r in self.client.query_and_wait(sql)]
