"""BigQuery writer: staging loads + MERGE upserts, child-row replacement."""

import logging
import os
import random
import time
import uuid
from typing import Any

from google.api_core.exceptions import BadRequest, Conflict
from google.cloud import bigquery

from .schema import TABLES

logger = logging.getLogger(__name__)

# Attempts for DML that can collide with a concurrent mutation of the same
# table (parallel webhook tasks, scheduled ticks)
_CONCURRENT_ATTEMPTS = 5


class BigQueryWriter:
    def __init__(self, project: str | None = None, dataset: str | None = None):
        self.project = project or os.environ["GCP_PROJECT_ID"]
        self.dataset = dataset or os.environ.get("BQ_DATASET", "brightpearl")
        self.client = bigquery.Client(project=self.project)

    def _load_json(self, rows: list[dict[str, Any]], target: str, job_config) -> None:
        """load_table_from_json with a fresh job id on 409 Conflict.

        A client-side timeout can re-submit a load with the same autogenerated
        job id; BigQuery rejects the duplicate even though the first attempt
        may have succeeded. Retrying with an explicit new id is always safe
        here because staging loads and truncate loads are WRITE_TRUNCATE.
        """
        try:
            self.client.load_table_from_json(rows, target, job_config=job_config).result()
        except Conflict:
            logger.warning("load job conflict on %s; retrying with fresh job id", target)
            self.client.load_table_from_json(
                rows, target, job_config=job_config, job_id=f"retry_{uuid.uuid4().hex}"
            ).result()

    def _table_ref(self, name: str) -> str:
        return f"{self.project}.{self.dataset}.{name}"

    def _dml(self, sql: str):
        """query_and_wait with backoff on concurrent-update aborts.

        BigQuery allows one mutating statement per table at a time; when two
        collide it aborts one with a 400 mentioning "concurrent update".
        Retrying is safe here: every mutation in this module is idempotent
        (keyed MERGEs, DELETE+INSERT transactions, soft-delete UPDATEs).
        """
        for attempt in range(_CONCURRENT_ATTEMPTS):
            try:
                return self.client.query_and_wait(sql)
            except BadRequest as e:
                if "concurrent update" not in str(e) or attempt == _CONCURRENT_ATTEMPTS - 1:
                    raise
                delay = 2**attempt + random.random()
                logger.warning(
                    "concurrent update abort (attempt %d/%d); retrying in %.1fs",
                    attempt + 1, _CONCURRENT_ATTEMPTS, delay,
                )
                time.sleep(delay)

    def ensure_tables(self) -> None:
        for name, spec in TABLES.items():
            table = bigquery.Table(self._table_ref(name), schema=spec["schema"])
            self.client.create_table(table, exists_ok=True)
        # Additive migrations for pre-existing tables
        self.client.query_and_wait(
            f"ALTER TABLE `{self._table_ref('sync_state')}` "
            "ADD COLUMN IF NOT EXISTS watermark_id INT64"
        )
        for table in ("orders", "products", "contacts"):
            self.client.query_and_wait(
                f"ALTER TABLE `{self._table_ref(table)}` "
                "ADD COLUMN IF NOT EXISTS is_deleted BOOL, "
                "ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP"
            )

    def mark_deleted(self, table: str, key_field: str, ids: list[int]) -> int:
        """Soft-delete records (destroyed webhooks / reconciliation sweeps)."""
        if not ids:
            return 0
        id_list = ", ".join(str(i) for i in ids)
        self._dml(
            f"UPDATE `{self._table_ref(table)}` "
            f"SET is_deleted = TRUE, deleted_at = CURRENT_TIMESTAMP() "
            f"WHERE {key_field} IN ({id_list}) AND NOT IFNULL(is_deleted, FALSE)"
        )
        return len(ids)

    def ensure_table(self, name: str, schema: list[bigquery.SchemaField]) -> None:
        table = bigquery.Table(self._table_ref(name), schema=schema)
        self.client.create_table(table, exists_ok=True)

    def _load_staging(
        self,
        name: str,
        rows: list[dict[str, Any]],
        schema: list[bigquery.SchemaField] | None = None,
    ) -> str:
        # Unique per operation: a webhook flush and a scheduled tick can hit
        # the same table concurrently and must not clobber each other's
        # staging. Callers drop the table in a finally block.
        staging = self._table_ref(f"_stg_{name}_{uuid.uuid4().hex[:8]}")
        self._load_json(
            rows,
            staging,
            bigquery.LoadJobConfig(
                schema=schema or TABLES[name]["schema"],
                write_disposition="WRITE_TRUNCATE",
            ),
        )
        return staging

    def _drop(self, table_ref: str) -> None:
        self.client.delete_table(table_ref, not_found_ok=True)

    def truncate_load(
        self, name: str, rows: list[dict[str, Any]], schema: list[bigquery.SchemaField]
    ) -> int:
        """Replace the whole table (small reference/mutable resources)."""
        self.ensure_table(name, schema)
        self._load_json(
            rows,
            self._table_ref(name),
            bigquery.LoadJobConfig(schema=schema, write_disposition="WRITE_TRUNCATE"),
        )
        return len(rows)

    def upsert(
        self,
        name: str,
        rows: list[dict[str, Any]],
        schema: list[bigquery.SchemaField] | None = None,
        key: str | None = None,
    ) -> int:
        """MERGE rows into the target table keyed on the table's key field.

        Staging is deduped on the key (keeping the freshest when_upserted) so
        overlapping pages or duplicate webhook deliveries stay idempotent.
        Schema/key come from TABLES unless supplied (dynamic search dumps).
        """
        if not rows:
            return 0
        if schema is None:
            spec = TABLES[name]
            schema, key = spec["schema"], spec["key_field"]
        staging = self._load_staging(name, rows, schema)
        target = self._table_ref(name)
        cols = [f.name for f in schema]
        updates = ", ".join(f"T.{c} = S.{c}" for c in cols if c != key)
        insert_cols = ", ".join(cols)
        insert_vals = ", ".join(f"S.{c}" for c in cols)
        sql = f"""
        MERGE `{target}` T
        USING (
          SELECT * EXCEPT(_rn) FROM (
            SELECT *, ROW_NUMBER() OVER (
              PARTITION BY {key} ORDER BY when_upserted DESC
            ) AS _rn
            FROM `{staging}`
          ) WHERE _rn = 1
        ) S
        ON T.{key} = S.{key}
        WHEN MATCHED THEN UPDATE SET {updates}
        WHEN NOT MATCHED THEN INSERT ({insert_cols}) VALUES ({insert_vals})
        """
        if name == "sync_state":
            sql = sql.replace("ORDER BY when_upserted DESC", "ORDER BY last_run_at DESC")
        try:
            self._dml(sql)
        finally:
            self._drop(staging)
        return len(rows)

    def replace_children(
        self,
        name: str,
        parent_field: str,
        parent_ids: list[int],
        rows: list[dict[str, Any]],
        schema: list[bigquery.SchemaField] | None = None,
    ) -> int:
        """Replace all child rows for the given parents (handles deleted lines).

        Delete + insert run in one BigQuery transaction so a crash between
        them can't leave parents without their rows.
        """
        if not parent_ids:
            return 0
        target = self._table_ref(name)
        cols = ", ".join(f.name for f in (schema or TABLES[name]["schema"]))
        ids = ", ".join(str(i) for i in parent_ids)
        delete_sql = f"DELETE FROM `{target}` WHERE {parent_field} IN ({ids});"
        if not rows:
            self._dml(delete_sql)
            return 0
        staging = self._load_staging(name, rows, schema)
        try:
            self._dml(
                "BEGIN TRANSACTION;\n"
                + delete_sql
                + f"\nINSERT INTO `{target}` ({cols}) SELECT {cols} FROM `{staging}`;\n"
                + "COMMIT TRANSACTION;"
            )
        finally:
            self._drop(staging)
        return len(rows)

    def query(self, sql: str) -> list[dict[str, Any]]:
        return [dict(r) for r in self.client.query_and_wait(sql)]
