"""BigQuery table definitions for the brightpearl dataset.

Principles (see GAMEPLAN.md): typed columns for every queryable field, one
native-JSON raw_payload per table for schema drift, audit columns everywhere.
"""

from google.cloud import bigquery

# key_field is the MERGE key. child_of marks tables replaced per-parent
# (delete parent's rows, insert fresh) instead of merged row-by-row.
TABLES: dict[str, dict] = {
    "orders": {
        "key_field": "order_id",
        "schema": [
            bigquery.SchemaField("order_id", "INT64", mode="REQUIRED"),
            bigquery.SchemaField("parent_order_id", "INT64"),
            bigquery.SchemaField("order_type_code", "STRING"),
            bigquery.SchemaField("reference", "STRING"),
            bigquery.SchemaField("order_status_id", "INT64"),
            bigquery.SchemaField("order_status_name", "STRING"),
            bigquery.SchemaField("order_payment_status", "STRING"),
            bigquery.SchemaField("stock_status_code", "STRING"),
            bigquery.SchemaField("allocation_status_code", "STRING"),
            bigquery.SchemaField("shipping_status_code", "STRING"),
            bigquery.SchemaField("placed_on", "TIMESTAMP"),
            bigquery.SchemaField("created_on", "TIMESTAMP"),
            bigquery.SchemaField("updated_on", "TIMESTAMP"),
            bigquery.SchemaField("closed_on", "TIMESTAMP"),
            bigquery.SchemaField("customer_contact_id", "INT64"),
            bigquery.SchemaField("customer_company_name", "STRING"),
            bigquery.SchemaField("customer_email", "STRING"),
            bigquery.SchemaField("delivery_state", "STRING"),
            bigquery.SchemaField("delivery_postal_code", "STRING"),
            bigquery.SchemaField("delivery_country_iso", "STRING"),
            bigquery.SchemaField("warehouse_id", "INT64"),
            bigquery.SchemaField("channel_id", "INT64"),
            bigquery.SchemaField("lead_source_id", "INT64"),
            bigquery.SchemaField("staff_owner_contact_id", "INT64"),
            bigquery.SchemaField("currency_code", "STRING"),
            bigquery.SchemaField("exchange_rate", "NUMERIC"),
            bigquery.SchemaField("total_net", "NUMERIC"),
            bigquery.SchemaField("total_tax", "NUMERIC"),
            bigquery.SchemaField("total", "NUMERIC"),
            bigquery.SchemaField("base_total_net", "NUMERIC"),
            bigquery.SchemaField("base_total", "NUMERIC"),
            bigquery.SchemaField("invoice_reference", "STRING"),
            bigquery.SchemaField("price_list_id", "INT64"),
            bigquery.SchemaField("historical_order", "BOOL"),
            bigquery.SchemaField("raw_payload", "JSON"),
            bigquery.SchemaField("when_upserted", "TIMESTAMP", mode="REQUIRED"),
        ],
    },
    "order_rows": {
        "key_field": "order_row_id",
        "child_of": ("orders", "order_id"),
        "schema": [
            bigquery.SchemaField("order_row_id", "INT64", mode="REQUIRED"),
            bigquery.SchemaField("order_id", "INT64", mode="REQUIRED"),
            bigquery.SchemaField("row_sequence", "INT64"),
            bigquery.SchemaField("product_id", "INT64"),
            bigquery.SchemaField("product_name", "STRING"),
            bigquery.SchemaField("product_sku", "STRING"),
            bigquery.SchemaField("quantity", "NUMERIC"),
            bigquery.SchemaField("item_cost", "NUMERIC"),
            bigquery.SchemaField("product_price", "NUMERIC"),
            bigquery.SchemaField("discount_percentage", "NUMERIC"),
            bigquery.SchemaField("row_net", "NUMERIC"),
            bigquery.SchemaField("row_tax", "NUMERIC"),
            bigquery.SchemaField("tax_rate", "NUMERIC"),
            bigquery.SchemaField("tax_code", "STRING"),
            bigquery.SchemaField("nominal_code", "STRING"),
            bigquery.SchemaField("bundle_parent", "BOOL"),
            bigquery.SchemaField("bundle_child", "BOOL"),
            bigquery.SchemaField("parent_order_row_id", "INT64"),
            bigquery.SchemaField("product_options", "JSON"),
            bigquery.SchemaField("order_updated_on", "TIMESTAMP"),
            bigquery.SchemaField("when_upserted", "TIMESTAMP", mode="REQUIRED"),
        ],
    },
    "products": {
        "key_field": "product_id",
        "schema": [
            bigquery.SchemaField("product_id", "INT64", mode="REQUIRED"),
            bigquery.SchemaField("sku", "STRING"),
            bigquery.SchemaField("barcode", "STRING"),
            bigquery.SchemaField("name", "STRING"),
            bigquery.SchemaField("status", "STRING"),
            bigquery.SchemaField("brand_id", "INT64"),
            bigquery.SchemaField("product_type_id", "INT64"),
            bigquery.SchemaField("product_group_id", "INT64"),
            bigquery.SchemaField("stock_tracked", "BOOL"),
            bigquery.SchemaField("weight", "NUMERIC"),
            bigquery.SchemaField("is_bundle", "BOOL"),
            bigquery.SchemaField("nominal_code_sales", "STRING"),
            bigquery.SchemaField("nominal_code_purchases", "STRING"),
            bigquery.SchemaField("nominal_code_stock", "STRING"),
            bigquery.SchemaField("created_on", "TIMESTAMP"),
            bigquery.SchemaField("updated_on", "TIMESTAMP"),
            bigquery.SchemaField("raw_payload", "JSON"),
            bigquery.SchemaField("when_upserted", "TIMESTAMP", mode="REQUIRED"),
        ],
    },
    "contacts": {
        "key_field": "contact_id",
        "schema": [
            bigquery.SchemaField("contact_id", "INT64", mode="REQUIRED"),
            bigquery.SchemaField("first_name", "STRING"),
            bigquery.SchemaField("last_name", "STRING"),
            bigquery.SchemaField("email", "STRING"),
            bigquery.SchemaField("telephone", "STRING"),
            bigquery.SchemaField("company_id", "INT64"),
            bigquery.SchemaField("organisation_name", "STRING"),
            bigquery.SchemaField("is_supplier", "BOOL"),
            bigquery.SchemaField("is_staff", "BOOL"),
            bigquery.SchemaField("price_list_id", "INT64"),
            bigquery.SchemaField("credit_term_days", "INT64"),
            bigquery.SchemaField("currency_id", "INT64"),
            bigquery.SchemaField("contact_tags", "STRING"),
            bigquery.SchemaField("created_on", "TIMESTAMP"),
            bigquery.SchemaField("updated_on", "TIMESTAMP"),
            bigquery.SchemaField("last_contacted_on", "TIMESTAMP"),
            bigquery.SchemaField("raw_payload", "JSON"),
            bigquery.SchemaField("when_upserted", "TIMESTAMP", mode="REQUIRED"),
        ],
    },
    "sync_state": {
        "key_field": "resource",
        "schema": [
            bigquery.SchemaField("resource", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("watermark_updated_on", "TIMESTAMP"),
            bigquery.SchemaField("last_run_at", "TIMESTAMP"),
            bigquery.SchemaField("last_run_kind", "STRING"),
            bigquery.SchemaField("last_run_rows", "INT64"),
        ],
    },
}
